name: My first workflow
on: [push]

jobs: 
  first_job:
    name: My first job
    runs-on: ubuntu-latest

    steps:
      - name: Great
        run: |
          echo "Hello world from ${{ github.actor }}"
        shell: bash

      - run: |
          echo "My secret is '${{ secrets.MY_SECRET }}"
        shell: bash
